'use client';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  Dumbbell, Apple, ScanLine, BarChart3, Zap, Shield,
  ArrowRight, CheckCircle, Crown, Sparkles, Menu, X
} from 'lucide-react';

export default function LandingPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  // If already logged in, go straight to dashboard
  useEffect(() => {
    if (status === 'authenticated') {
      router.push('/dashboard');
    }
  }, [status, router]);

  if (status === 'loading' || status === 'authenticated') {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-3 border-primary-500/30 border-t-primary-500 rounded-full spinner" />
      </div>
    );
  }

  return <LandingContent />;
}

function LandingContent() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const features = [
    {
      icon: Dumbbell,
      title: 'AI Workout Plans',
      desc: 'Personalised training programs generated by AI that adapt to your goals, experience level, and available equipment.',
      badges: ['Personalised', 'Progressive', 'Adaptive'],
    },
    {
      icon: Apple,
      title: 'AI Meal Plans',
      desc: 'Custom nutrition plans with macro tracking, meal substitutions, and dietary preference support.',
      badges: ['Macro tracking', 'Substitutions', 'Dietary prefs'],
    },
    {
      icon: ScanLine,
      title: 'Barcode Scanner',
      desc: 'Instantly log food by scanning barcodes. Automatic nutritional data lookup with one tap.',
      badges: ['Instant lookup', 'Camera scan', 'Auto-log'],
    },
    {
      icon: BarChart3,
      title: 'Progress Tracking',
      desc: 'Visual charts for weight, workouts, and nutrition. See trends and stay motivated with data-driven insights.',
      badges: ['Weight charts', 'Workout logs', 'Trends'],
    },
    {
      icon: Zap,
      title: 'AI Assessments',
      desc: 'Get smart feedback on your performance. AI analyses your progress and suggests improvements.',
      badges: ['Performance', 'Suggestions', 'Smart feedback'],
    },
    {
      icon: Shield,
      title: 'Privacy First',
      desc: 'Your data stays on your device. No social features, no sharing — just you and your fitness journey.',
      badges: ['Local storage', 'No tracking', 'Secure'],
    },
  ];

  const steps = [
    { num: '01', title: 'Create Account', desc: 'Sign up in seconds with email or Google' },
    { num: '02', title: 'Set Your Goals', desc: 'Tell us your fitness goals and experience level' },
    { num: '03', title: 'Get Your Plan', desc: 'AI generates personalised workout and meal plans' },
    { num: '04', title: 'Track & Improve', desc: 'Log workouts, scan food, and watch your progress' },
  ];

  return (
    <div className="min-h-screen overflow-x-hidden">
      {/* Nav */}
      <nav className="sticky top-0 z-50 bg-surface/90 backdrop-blur-lg border-b border-dark-700/50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex items-center justify-between h-16">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center">
              <Dumbbell className="text-white" size={18} />
            </div>
            <span className="text-xl font-bold text-dark-100">Nexal</span>
          </div>

          {/* Desktop nav */}
          <div className="hidden sm:flex items-center gap-6">
            <a href="#features" className="text-sm text-dark-400 hover:text-dark-200 transition-colors">Features</a>
            <a href="#how-it-works" className="text-sm text-dark-400 hover:text-dark-200 transition-colors">How It Works</a>
            <a href="#pricing" className="text-sm text-dark-400 hover:text-dark-200 transition-colors">Pricing</a>
            <Link href="/login" className="text-sm font-medium text-dark-300 hover:text-dark-100 transition-colors">Sign In</Link>
            <Link href="/register" className="text-sm font-medium px-4 py-2 rounded-xl bg-gradient-to-r from-primary-500 to-primary-600 text-white hover:from-primary-600 hover:to-primary-700 transition-all shadow-sm">
              Get Started
            </Link>
          </div>

          {/* Mobile menu button */}
          <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="sm:hidden p-2 text-dark-400">
            {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div className="sm:hidden border-t border-dark-700/50 bg-surface px-4 py-4 space-y-3">
            <a href="#features" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-dark-400 py-2">Features</a>
            <a href="#how-it-works" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-dark-400 py-2">How It Works</a>
            <a href="#pricing" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-dark-400 py-2">Pricing</a>
            <Link href="/login" className="block text-sm font-medium text-dark-300 py-2">Sign In</Link>
            <Link href="/register" className="block text-center text-sm font-medium px-4 py-3 rounded-xl bg-gradient-to-r from-primary-500 to-primary-600 text-white">
              Get Started Free
            </Link>
          </div>
        )}
      </nav>

      {/* Hero */}
      <section className="px-4 sm:px-6 pt-16 pb-20 text-center max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary-50 border border-primary-200 text-primary-700 text-xs font-medium mb-6">
          <Sparkles size={14} />
          AI-Powered Fitness Coach
        </div>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-dark-100 leading-tight mb-6">
          Your Personal
          <br />
          <span className="gradient-text">AI Fitness Coach</span>
        </h1>

        <p className="text-lg sm:text-xl text-dark-400 max-w-2xl mx-auto mb-10 leading-relaxed">
          Start with a 7-day free trial. Get AI-generated workout plans, personalised meal plans,
          barcode food scanner, and progress tracking — all for just $4.99/month.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-8">
          <Link
            href="/register"
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-4 rounded-xl bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold text-lg hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg shadow-primary-500/25"
          >
            Start Free Trial
            <ArrowRight size={20} />
          </Link>
          <Link
            href="/login"
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-4 rounded-xl border border-dark-700 text-dark-300 font-medium hover:bg-dark-950 transition-all"
          >
            Sign In
          </Link>
        </div>

        <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-dark-500">
          <span className="flex items-center gap-1.5"><CheckCircle size={15} className="text-primary-500" /> No credit card required</span>
          <span className="flex items-center gap-1.5"><CheckCircle size={15} className="text-primary-500" /> 7-day free trial</span>
          <span className="flex items-center gap-1.5"><CheckCircle size={15} className="text-primary-500" /> Cancel anytime</span>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="px-4 sm:px-6 py-20 bg-dark-950/50">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-sm font-medium text-primary-500 uppercase tracking-wide mb-2">Platform Features</p>
            <h2 className="text-3xl sm:text-4xl font-bold text-dark-100">Everything You Need to Get Fit</h2>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div key={f.title} className="bg-surface rounded-2xl border border-dark-700/50 p-6 hover:shadow-lg hover:shadow-primary-500/5 transition-all duration-300">
                <div className="w-12 h-12 rounded-xl bg-primary-500/10 flex items-center justify-center mb-4">
                  <f.icon className="text-primary-500" size={24} />
                </div>
                <h3 className="text-lg font-semibold text-dark-100 mb-2">{f.title}</h3>
                <p className="text-sm text-dark-400 leading-relaxed mb-4">{f.desc}</p>
                <div className="flex flex-wrap gap-1.5">
                  {f.badges.map((b) => (
                    <span key={b} className="text-xs px-2 py-1 rounded-lg bg-dark-950 text-dark-400 border border-dark-700/50">
                      {b}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="px-4 sm:px-6 py-20">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-sm font-medium text-primary-500 uppercase tracking-wide mb-2">How It Works</p>
            <h2 className="text-3xl sm:text-4xl font-bold text-dark-100">Get Started in Minutes</h2>
            <p className="text-dark-400 mt-3">No complex setup or learning curve.</p>
          </div>

          <div className="grid sm:grid-cols-2 gap-6">
            {steps.map((step) => (
              <div key={step.num} className="flex items-start gap-4 p-5 rounded-2xl bg-surface border border-dark-700/50">
                <div className="w-10 h-10 rounded-xl bg-primary-500/10 flex items-center justify-center flex-shrink-0">
                  <span className="text-sm font-bold text-primary-500">{step.num}</span>
                </div>
                <div>
                  <h3 className="font-semibold text-dark-100 mb-1">{step.title}</h3>
                  <p className="text-sm text-dark-400">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="px-4 sm:px-6 py-20 bg-dark-950/50">
        <div className="max-w-lg mx-auto text-center">
          <p className="text-sm font-medium text-primary-500 uppercase tracking-wide mb-2">Pricing</p>
          <h2 className="text-3xl sm:text-4xl font-bold text-dark-100 mb-4">Simple, Affordable Pricing</h2>
          <p className="text-dark-400 mb-10">Start free, upgrade when you&#39;re ready.</p>

          <div className="bg-surface rounded-2xl border-2 border-primary-500/30 p-8 shadow-lg shadow-primary-500/5">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-50 text-primary-600 text-xs font-medium mb-4">
              <Crown size={14} />
              Nexal Premium
            </div>

            <div className="flex items-baseline justify-center gap-1 mb-2">
              <span className="text-5xl font-bold text-dark-100">$4.99</span>
              <span className="text-dark-400 text-lg">/month</span>
            </div>
            <p className="text-sm text-dark-500 mb-6">After 7-day free trial</p>

            <div className="space-y-3 text-left mb-8">
              {[
                'AI-generated workout plans',
                'Personalised meal plans with macros',
                'Barcode food scanner',
                'Progress charts & insights',
                'AI performance assessments',
                'Unlimited access to all features',
              ].map((item) => (
                <div key={item} className="flex items-center gap-3">
                  <CheckCircle className="text-primary-500 flex-shrink-0" size={18} />
                  <span className="text-sm text-dark-300">{item}</span>
                </div>
              ))}
            </div>

            <Link
              href="/register"
              className="w-full flex items-center justify-center gap-2 px-6 py-4 rounded-xl bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg shadow-primary-500/25"
            >
              Start 7-Day Free Trial
              <ArrowRight size={18} />
            </Link>

            <p className="text-xs text-dark-500 mt-4">No credit card required to start. Cancel anytime.</p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-4 sm:px-6 py-20">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-dark-100 mb-4">Ready to Transform Your Fitness?</h2>
          <p className="text-dark-400 mb-8">Join thousands using AI to reach their fitness goals faster.</p>
          <Link
            href="/register"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold text-lg hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg shadow-primary-500/25"
          >
            Get Started Today
            <ArrowRight size={20} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-4 sm:px-6 py-10 border-t border-dark-700/50">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center">
              <Dumbbell className="text-white" size={12} />
            </div>
            <span className="text-sm font-semibold text-dark-300">Nexal</span>
          </div>
          <div className="flex items-center gap-6 text-xs text-dark-500">
            <Link href="/login" className="hover:text-dark-300 transition-colors">Sign In</Link>
            <Link href="/register" className="hover:text-dark-300 transition-colors">Register</Link>
          </div>
          <p className="text-xs text-dark-600">&copy; {new Date().getFullYear()} Nexal. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
